// ********* LOCAL LINKS  ********* //
// ********* LOCAL LINKS  ********* //

###
#User registration
###
# POST /users/register
POST http://localhost:9000/users/register
Content-Type: application/json

{
  "name": "Michael Scott",
  "email": "littlekidlover@gmail.com",
  "password": "hello1234"
}

###
# User Login
###

# POST /users/login
POST http://localhost:9000/users/login
Content-Type: application/json

{
  "login": "scrantonforever@gmail.com",
  "password": "hello1234"
}

###
# User Logout
###

# GET /users/logout
GET http://localhost:9000/users/logout

###
# Get User Profile
###

# GET /users/profile
GET http://localhost:9000/users/profile

###
# Update User Profile with Password Verification
###

# PUT /users/profile
PUT http://localhost:9000/users/profile
Content-Type: application/json

{
  "name": "Michael Scott",
  "email": "scrantonforever@gmail.com",
  "password": "hello1234",
  "username": "mscott"
}

// ********* RENDER LINKS  ********* //
// ********* RENDER LINKS  ********* //
