// ********* LOCAL LINKS  ********* //
// ********* LOCAL LINKS  ********* //

###
#Create swap
###
# POST /swaps/
POST http://localhost:9000/swaps/
Content-Type: application/json

{
    "user":"6699612b9290d13acb5bf756",
    "book":"667f8e927be85037cf3b746b",
    "Description":"Willing to trade for a hardcover fantasy book.",
    "Location":"Bentonville, Arksansas"
}


###
# Get all swaps
###

# GET /swaps/
GET http://localhost:9000/swaps/

###
# Get single swap
###

# GET /swaps/:id
GET http://localhost:9000/swaps/669ac33e2b8b2fc8920fd8b9

###
# Update Swap (user must be the creator of the swap)
###

# PUT /swaps/:id
PUT http://localhost:9000/swaps/669ac33e2b8b2fc8920fd8b9
Content-Type: application/json

{
    "user":"667c836fd4985e072a44e1ca",
    "book":"667f8e927be85037cf3b746b",
    "Description":"Willing to trade for a hardcover fantasy book.",
    "Location":"Bryant, Arksansas"
}


###
#Delete Swap
###
# Delete /swaps/:id
Delete http://localhost:9000/swaps/669897e91c5845b65b08decd
###



// ********* Render LINKS  ********* //
// ********* Render LINKS  ********* //

###
#Create swap (must be login)
###
# POST /swaps/
POST https://book-barter.onrender.com/swaps/
Content-Type: application/json

{
    "user":"66995366cd8732b739e5bc46",
    "book":"667f8e927be85037cf3b746b",
    "Description":"Willing to trade for a hardcover fantasy book.",
    "Location":"Santaville, North Pole"
}


###
# Get all swaps
###

# GET /swaps/
GET https://book-barter.onrender.com/swaps/

###
# Get single swap
###

# GET /swaps/:id
GET https://book-barter.onrender.com/swaps/66989431ea1202792f61a39c

###
# Update Swap (user must be the creator of the swap)
###

# PUT /swaps/:id
PUT https://book-barter.onrender.com/swaps/6695effd0e73de4e8adabe83
Content-Type: application/json

{
    "user":"6680374d84ac2a468db8b1b3",
    "book":"667f8e927be85037cf3b746b",
    "Description":"Willing to trade for a hardcover fantasy book.",
    "Location":"Fort Smith, Arksansas"
}


###
#Delete Swap
###
# Delete /swaps/:id
Delete https://book-barter.onrender.com/swaps/66989431ea1202792f61a39c
###