// ********* LOCAL LINKS  ********* //
// ********* LOCAL LINKS  ********* //

###
#User registration
###
# POST /users/register
POST http://localhost:9000/users/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@example.com",
  "password": "hello1234",
  "username": "testuser"
}

###
# User Login
###

# POST /users/login
POST http://localhost:9000/users/login
Content-Type: application/json

{
  "login": "mscott",
  "password": "hello1234"
}

###
# User Logout
###
# GET /users/logout
GET http://localhost:9000/users/logout

###
# Get User Profile
###

# GET /users/profile
GET http://localhost:9000/users/profile

###
# Update User Profile with Password Verification
###

# PUT /users/profile
PUT http://localhost:9000/users/profile
Content-Type: application/json

{
  "name": "Michael Scott",
  "email": "scrantonforever@gmail.com",
  "password": "hello1234",
  "username": "mscott"
}


// ********* RENDER LINKS  ********* //
// ********* RENDER LINKS  ********* //


###
#User registration
###
# POST /users/register
POST http://book-barter.onrender.com/users/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "Password123",
  "username": "johndoe"
}

###
# User Login
###

# POST /users/login
POST http://book-barter.onrender.com/users/login
Content-Type: application/json

{
  "login": "scrantonforever20@gmail.com",
  "password": "hello1234"
}

###
# User Logout
###

# GET /users/logout
GET http://book-barter.onrender.com/users/logout

###
# Get User Profile
###

# GET /users/profile
GET http://book-barter.onrender.com/users/profile

###
# Update User Profile with Password Verification
###

# PUT /users/profile
PUT http://book-barter.onrender.com/users/profile
Content-Type: application/json

{
  "name": "Michael Scott",
  "email": "scrantonforever@gmail.com",
  "password": "",
  "username": ""
}
